import i18n from "i18next";
import { initReactI18next } from "react-i18next";

const savedLang = localStorage.getItem("lang");
const defaultLang = savedLang || "en";

const resources = {
  en: {
    translation: {
      font: "font-poppins",
      dir: "ltr",
      topHeader: "Discover attractive products at unbeatable prices.",
      shop: "Talk to Us",
      welcome: "Welcome to the E-Commerce Website",

      home: "Home",
      contact: "Contact",
      about: "About",
      signUp: "Sign Up",
      account: "My Account",
      Dashboard: "Dashboard",
      manager: "Become A Manager",
      dashboardNavs: {
        home: "Dashboard",
        customers: "Customers",
        products: "Products",
        orders: "Orders",
        sales: "Sales",
        statistics: "Statistics",
        topNav: {
          hello: "hello Again!",
        },
      },
      orderPage: {
        underivered: "Undelivered Orders",
        derivered: "Delivered Orders",
        canceled: "Canceled Orders",
        underivNotFound: "",
        derivNotFound: "",
        cancelNotFound: "",
      },
      orderCard: {
        orderId: "Order ID",
        orderStatus: "Order Status",
        orderDate: "Order Date",
        products: "Products",
        totalPrice: "Total Price",
        cancelOrder: "Cancel Order",
      },
      headerIcons: {
        1: "Manage My Account",
        2: "My Order",
        3: "My Cancellations",
        4: "My Reviews",
        5: "Logout",
      },
      search: "Search...",

      homeSections: {
        row1: {
          col1: [
            "Agriculture",
            "Handicrafts",
            "Food",
            "Textiles",
            "Cosmetics and Personal Care",
            "Energy and Resources",
            "Chemicals",
          ],
          col2: ["iPhone 14 Series", "Up to 10% off Voucher", "Shop Now"],
        },
        row2: ["Today’s", "Agriculture", "Days", "Hours", "Minutes", "Seconds"],
        row3: {
          header: "B2B E-commerce Made for Your Business",
          body: "Explore a platform designed for businesses to source high-quality products in bulk. At Team Tchad Export, we cater exclusively to business needs.",
        },
      },
      removeFromCart: "Remove from Cart",
      addToCart: "Add to Cart",
      new: "NEW",
      Search: {
        all: "All",
        category: "Category",
        min: "Min",
        max: "Max",
        placeholder: "Search Products",
      },
      item: {
        discount: "Discount",
        expires: "Expiration Date",
        availQuantity: "Available Quantity",
        MOQ: "Minimum Order Quantity(MOQ)",
        quantity: "Quantity",
        addCart: "Add To Cart",
        addedToCart: "Product already in cart",
      },
      alerts: {
        wishes: {
          success: "",
        },
      },
      categories: {
        general: "General",
        newArrival: "New Arrival",
        agriculture: "Agriculture",
        handicrafts: "Handicrafts",
        food: "Food",
        textiles: "Textiles",
        cosmetics: "Cosmetics",
        energyAndResources: "Energy and Resources",
        chemicals: "Chemicals",
      },
      services: {
        0: {
          value: "FREE AND FAST DELIVERY",
          description: "Free delivery for all orders over $140 ",
        },

        1: {
          value: "24/7 CUSTOMER SERVICE",
          description: "Friendly 24/7 customer support",
        },
        2: {
          value: "MONEY BACK GUARANTEE",
          description: "We return money within 30 days",
        },
      },
      redButtons: {
        viewAllProducts: "View All Products",
        viewAll: "View All",
        exploreByCategory: "Explore By Category",
        buyNow: "Buy Now",
        sendMassage: "Send Message",
        createAccount: "Create Account",
        login: "Log In",
        applyCoupon: "Apply Coupon",
        processToCheckout: "Proceed to Checkout",
        placeOrder: "Place Order",
        backToHomePage: "Back to Home Page",
        chooseByCategory: "Choose By Category",
        createOrder: "Create an Order",
      },
      whiteButtons: {
        backToHomePage: "Back to Home Page",
        loadMore: "Load More...",
        moveAllToBag: "Move All to Bag",
        seeAll: "See All",
        returnToShop: "Return to Shop",
        updateCart: "Update Cart",
      },

      wishlist: {
        title: "Wishlist",
        justForYou: "Just for you",
        noWishes: "No Wishes",
      },
      cart: {
        header: {
          product: "Product",
          price: "Price",
          quantity: "Quantity",
          subtotal: "Subtotal",
        },
        cartTotal: "Cart Total",
        total: "Total",
        totalItems: "Total Items",
        shipping: "Shipping",
        free: "Free",
        emptyCart: "Your cart is empty.",
      },
      checkOut: {
        title: "Checkout",
        billingDetails: "Billing Details",
        firstName: "First Name",

        company: "Company Name",
        Country: "Country",
        address: "Street Address",
        city: "Town / City",
        phone: "Phone",
        email: "Email Address",
        apartment: "Apartment, floor, etc. (optional)",
        methods: "Payment Methods",
        bank: "Bank (Visa)",
        cash: "Cash on Delivery",
        couponCode: "Coupon Code",
        postalCode: "Postal Code",
        province: "Province",
        district: "District",
      },
      payment: {
        payment: "Payment Details",
        number: "Card Number",
        enter: "Enter your card number",
        expirationDate: "Expiration Date",
      },
      productPage: {
        relatedItems: "Related Items",
        quantity: "quantity",
        size: "Size",
        inStock: "In Stock",
        reviews: "Reviews",
        review: "Review",
        1: "Free Delivery",
        1.1: "Enter your postal code for Delivery Availability",
        2: "Return Delivery",
        2.1: "Free 30 Days Delivery Returns. Details",
      },
      contactPage: {
        call: "Call To Us",
        available: "We are available 24/7, 7 days a week.",
        phone: "Phone",
        write: "Write To Us",
        fillForm: "Fill out our form and we will contact you within 24 hours.",
        emails: "Emails",
        yourName: "Your Name",
        yourEmail: "Your Email",
        phoneNumber: "Your Phone Number",
        yourMessage: "Your Message",
      },
      aboutPage: {
        title: "About",
        story: "Our Story",
        paragraph1:
          "Launched in 2024, Team-Tchad Export is a premier online shopping marketplace with an active presence in Chad. Supported by a wide range of tailored marketing, data, and service solutions, Team-Tchad Export hosts 10,500 sellers and 300 brands, serving 3 million customers across the region.",
        paragraph2:
          "Team-Tchad Export offers more than 1 million products, growing at a rapid pace. The marketplace provides a diverse assortment of categories, catering to various consumer needs.",
        card1: "Sellers active on our site",
        card2: "Monthly Product Sales",
        card3: "Customers active on our site",
        card4: "Annual gross sale on our site",
        k1: "10.5k",
        k2: "33k",
        k3: "45.5k",
        k4: "25k",
        name1: "Tom Cruise",
        name2: "Tom Hanks",
        name3: "Will Smith",
        name4: "Tom Hardy",
        job1: "Founder & Chairman",
        job2: "CTO",
        job3: "CEO",
        job4: "Product Designer",
      },
      accountPage: {
        setMassage: "Account details updated successfully!",
        welcome: "Welcome! ",
        home: "Home",
        myAccount: "My Account",
        ManageMyAccount: "Manage My Account",
        myProfile: "My Profile",
        addressBook: "Address Book",
        myPaymentOptions: "My Payment Options",
        myOrders: "My Orders",
        myReturns: "My Returns",
        myCancelations: "My Cancelations",
        myWishlist: "My Wishlist",
        editYourProfile: "Edit Your Profile",
        firstName: "First Name",
        yourFirstName: "your first name",
        lastName: "Last Name",
        yourLastName: "your last name",
        email: "Email",
        yourEmail: "your email",
        phoneNumber: "Telephone",
        province: "Province",
        city: "City",
        street: "Street",
        zipcode: "Zipcode",
        profilePic: "Profile Picture",
        drop: "Drop the image here",
        dragNdrop: "Drag 'n' drop an image here, or click to select one",
        select: "Selected file",
        address: "Address",
        yourAddress: "your address",
        passwordChanges: "Password Changes",
        currentPassword: "Current Password",
        newPassword: "New Password",
        confirmPassword: "Confirm Password",
        cancel: "Cancel",
        saveChanges: "Save Changes",
      },

      signUpPage: {
        title: "Create an account",
        enter: "Enter your details below:",
        firstname: "Firstname",
        lastname: "Lastname",
        phoneNumber: "Telephone",
        email: "Email",
        password: "Password",
        createAccount: "Create Account",
        withGoogle: "Sign up with Google",
        haveAccount: "Already have an account?",
        login: "Log in",
      },
      loginPage: {
        title: "Log in to Exclusive",
        enter: "Enter your details below:",
        email: "Email ",
        password: "Password",
        forgot: "Forgot Password?",
        notHaveAccount: "Don't have an account?",
        login: "Log In",
        rememberMe: "Rememember Me",
        or: "or",
        googleLogin: "log in with Google",
      },
      Snackbar: {
        inCart: "Items already in the cart!",
        movedToCart: "Items moved to the cart successfully!",
        noItems: "No items to move to the cart!",
      },
      category: {
        redTitle: "Categories",
        title: "Browse By Category",
        categories: {
          0: "Agriculture",
          1: "Handicrafts",
          2: "Food",
          3: "Textiles",
          4: "Cosmetics",
          5: "Energy and Resources",
          6: "Chemicals",
        },
      },
      bestSelling: {
        redTitle: "This Month",
        title: "Best Selling Products",
      },
      deal: {
        greenTitle: "Categories",
        title: "Enhance Your Listing of  favorite Products with us",
        days: "Days",
        hours: "Hours",
        inutes: "Minutes",
        seconds: "Seconds",
        buyNow: "Buy Now!",
      },
      allProducts: {
        redTitle: "Our Products",
        title: "Explore Our Products",
        products: "All Products",
        byCategory: "Explore By Category",
        orders: "Orders",
      },
      featured: {
        redTitle: "Featured",
        title: "Featured Tchadian Products Spotlight",
        shopNow: "Shop Now",
        agriculture: {
          title: "Coffee",
          description: "High-quality coffee.",
        },
        handicrafts: {
          title: "Wooden Carvings",
          description: "Exquisite handcrafted wooden carvings.",
        },
        food: {
          title: "Banana",
          description: "Good quality bananas.",
        },
        textiles: {
          title: "Cotton Fabric",
          description: "Premium quality cotton fabric.",
        },
        cosmetics: {
          title: "Lipstick",
          description: "Best lipstick ever.",
        },
        energyAndResources: {
          title: "Solar Panel",
          description: "Efficient solar panels for renewable energy.",
        },
        chemicals: {
          title: "Cleaning Agent",
          description: "Eco-friendly cleaning agents.",
        },
      },
      footer: {
        subscribe: "Subscribe",
        offer: "Get 10% off your first order",
        enterEmail: "Enter your email",
        enterPassword: "Enter your password",
        account: "Account",
        myAccount: "My Account",
        sign: "Login / Register",
        cart: "Cart",
        wishlist: "Wishlist",
        shop: "Shop",
        downloadApp: "Download App",
        save: "Save $3 with App New User Only",
        support: "Support",
        address: "111 Bijoy sarani, Dhaka, DH 1515, Bangladesh",
        quickLinks: "Quick Links",
        privacy: "Privacy Policy",
        usage: "Terms Of Use",
        FAQ: "FAQ",
        Contact: "Contact",
        copyrights: "© Copyright Team Tchad Export 2024. All rights reserved",
        allRightsReserved: "© All rights reserved",
      },
      dashTopNav: {
        hello: "Hello",
        todayIs: "Today Is",
        daysOfWeek: {
          0: "Sunday",
          1: "Monday",
          2: "Tuesday",
          3: "Wednesday",
          4: "Thursday",
          5: "Friday",
          6: "Saturday",
        },
        monthsOfYear: {
          0: "January",
          1: "February",
          2: "March",
          3: "April",
          4: "May",
          5: "June",
          6: "July",
          7: "August",
          8: "September",
          9: "October",
          10: "November",
          11: "December",
        },
      },
      dashboard: {
        orderComp:{
          backToOrders: "Back to Orders",
          shippingAddress: "Shipping Address",
          street: "Street",
          city: "City",
          province: "Province",
          district: "District",
          orderInformation: "Order Information",
          orderStatus: "Order Status",
          totalPrice: "Total Price",
          paymentMethod: "Payment Method",
          approveOrder: "Approve Order",
          rejectOrder: "Reject Order",
          approving: "Approving...",
          rejecting: "Rejecting...",
          confirmDelivery: "Confirm Delivery",
          confirmingDelivery: "Confirming Delivery...",
          products: "Products",
          price: "Price",
          quantity: "Quantity",
          units: "Units",
          noOrderFound: "No order found.",
          failedToFetchOrder: "Failed to fetch order details:",
          failedToUpdateOrderStatus: "Failed to update order status!",
          orderStatusUpdated: "Order status updated successfully!",
          failedToUpdateDeliveryStatus: "Failed to update delivery status",
          deliveryConfirmed: "Delivery confirmed!",
        },
        cardNames: {
          revenue: "Revenue",
          customers: "Customers",
        },
        next: "Next",
        previous: "Previous",
        users: {
          allUsers: "All Users",
          role: "Role",
          users: "Users",
          findUser: "find a User...",
          profile: "Profile Picture",
          userId: "User ID",
          firstName: "First Name",
          lastName: "Last Name",
          email: "Email",
          phoneNumber: "Phone Number",
          status: "Status",
          joinedAt: "Joined At",
          action: "Action",
        },
        products: {
          createProduct:"Create Product",
          allProducts: "All Products",
          searchPlaceholder: "Search by title",
          minPricePlaceholder: "Min price",
          maxPricePlaceholder: "Max price",
          allCategories: "All Categories",
          noImage: "No image",
          noProductsFound: "No products found.",
          image: "Image",
          title: "Title",
          price: "Price",
          moq: "MOQ",
          category: "Category",
          quantity: "Quantity",
          owner: "Owner",
          actions: "Actions",
          edit: "Edit",
          delete: "Delete",
          more: "More",
          previous: "Previous",
          next: "Next",
          loading: "Loading Products...",
          error: "Error fetching products. Please try again later.",
        },
        allSales:"All Sales",
        orders: {
          allOrders: "All Orders",
          searchPlaceholder: "Search by order ID or customer name",
          orderID: "Order ID",
          orderer: "Orderer",
          products: "Products",
          date: "Date",
          orderStatus: "Order Status",
          deliveryStatus: "Delivery Status",
          totalPrice: "Total Price",
          totalQuantity: "Total Quantity",
          status: "Status",
          totalAmount: "Total Amount",
          paymentMethod: "Payment Method",
          shippingAddress: "Shipping Address",
          noOrdersFound: "No orders found.",
          actions: "Actions",
          view: "View",
          edit: "Edit",
          delete: "Delete",
          loading: "Loading Orders...",
          error: "Error fetching orders. Please try again later.",
          previous: "Previous",
          next: "Next",
          orderStatusOptions: {
            pending: "Pending",
            approved: "Approved",
            rejected: "Rejected",
            delivered: "Delivered",
          },
          deliveryFilterOptions: {
            allDeliveries: "All Deliveries",
            delivered: "Delivered",
            notDelivered: "Not Delivered",
          },
        },
        statistics:{
          reportTitle: "Statistics Report",
          usersByRole: "Users by Role",
          productsByCategory: "Products by Category",
          ordersOverview: "Orders Overview",
          monthlyRevenue: "Monthly Revenue",
          topProducts: "Top Products",
          userGrowth: "User Growth",
          generateReport: "Generate Report",
        }
      },
    },
  },



  fr: {
    translation: {
      font: "font-poppins",
      dir: "ltr",
      topHeader: "Découvrez des produits attrayants à des prix imbattables",
      shop: "Achetez maintenant",
      welcome: "Bienvenue sur le site de commerce électronique",

      home: "Accueil",
      contact: "Contact",
      about: "À propos",
      signUp: "S'inscrire",
      account: "Mon Compte",
      Dashboard: "Tableau de Bord",
      manager: "Devenir Manager",
      dashboardNavs: {
        home: "Tableau de bord",
        customers: "Clients",
        products: "Produits",
        orders: "Commandes",
        sales: "Ventes",
        statistics: "Statistiques",
        topNav: {
          hello: "Bonjour à nouveau !",
        },
      },
      headerIcons: {
        1: "Gérer Mon Compte",
        2: "Ma Commande",
        3: "Mes Annulations",
        4: "Mes Avis",
        5: "Déconnexion",
      },
      orderPage: {
        underivered: "Commandes non livrées",
        derivered: "Commandes livrées",
        canceled: "Commandes annulées",
        underivNotFound: "Aucune commande non livrée trouvée",
        derivNotFound: "Aucune commande livrée trouvée",
        cancelNotFound: "Aucune commande annulée trouvée",
      },
      orderCard: {
        orderId: "ID de commande",
        orderStatus: "Statut de la commande",
        orderDate: "Date de commande",
        products: "Produits",
        totalPrice: "Prix total",
        cancelOrder: "Annuler la commande",
      },
      search: "Recherche...",
      homeSections: {
        row1: {
          col1: [
            "Agriculture",
            "Artisanat",
            "Alimentation",
            "Textile",
            "Cosmétiques et Soins Personnels",
            "Énergie et Ressources",
            "Produits Chimiques",
          ],
          col2: [
            "Série iPhone 14",
            "Jusqu'à 10% de réduction",
            "Achetez maintenant",
          ],
        },
        row2: [
          "Aujourd'hui",
          "Agriculture",
          "Jours",
          "Heures",
          "Minutes",
          "Secondes",
        ],
        row3: {
          header: "Une plateforme e-commerce B2B pour votre entreprise",
          body: "Découvrez une plateforme conçue pour les entreprises afin de trouver des produits de qualité en gros. Chez Team Tchad Export, nous répondons exclusivement aux besoins des entreprises.",
        },
      },
      removeFromCart: "Retirer du Panier",
      addToCart: "Ajouter au Panier",
      new: "NOUVEAU",
      Search: {
        all: "Tous",
        category: "Catégorie",
        min: "Min",
        max: "Max",
        placeholder: "Rechercher des produits",
      },
      item: {
        discount: "Remise",
        expires: "Date d'expiration",
        availQuantity: "Quantité disponible",
        MOQ: "Quantité minimale de commande(QMC)",
        quantity: "Quantité",
        addCart: "Ajouter au panier",
        addedToCart: "Produit déjà dans le panier",
      },
      categories: {
        general: "Général",
        newArrival: "Nouveautés",
        agriculture: "Agriculture",
        handicrafts: "Artisanat",
        food: "Alimentation",
        textiles: "Textiles",
        cosmetics: "Cosmétiques",
        energyAndResources: "Énergie et Ressources",
        chemicals: "Produits Chimiques",
      },
      services: {
        0: {
          value: "LIVRAISON GRATUITE ET RAPIDE",
          description:
            "Livraison gratuite pour toutes les commandes de plus de 140 $",
        },

        1: {
          value: "SERVICE CLIENT 24/7",
          description: "Support client amical 24/7",
        },
        2: {
          value: "GARANTIE DE REMBOURSEMENT",
          description: "Nous remboursons l'argent sous 30 jours",
        },
      },
      redButtons: {
        viewAllProducts: "Voir Tous les Produits",
        viewAll: "Voir Tout",
        exploreByCategory: "Explorer par Catégorie",
        buyNow: "Achetez Maintenant",
        sendMassage: "Envoyer un Message",
        createAccount: "Créer un Compte",
        login: "Se Connecter",
        applyCoupon: "Appliquer le Coupon",
        processToCheckout: "Passer à la Caisse",
        placeOrder: "Passer la Commande",
        backToHomePage: "Retour à la Page d'Accueil",
        chooseByCategory: "Choisir par Catégorie",
        createOrder: "create un Ordre",
      },
      whiteButtons: {
        backToHomePage: "Retour à la Page d'Accueil",
        loadMore: "Charger Plus..",
        moveAllToBag: "Tout Déplacer dans le Panier",
        seeAll: "Voir Tout",
        returnToShop: "Retourner à la Boutique",
        updateCart: "Mettre à Jour le Panier",
      },

      wishlist: {
        title: "Liste de Souhaits",
        justForYou: "Juste pour vous",
        noWishes: "Aucun souhait",
      },
      cart: {
        header: {
          product: "Produit",
          price: "Prix",
          quantity: "Quantité",
          subtotal: "Sous-total",
        },
        cartTotal: "Total du Panier",
        total: "Total",
        totalItems: "Produits au total",
        shipping: "Livraison",
        free: "Gratuit",
        emptyCart: "Votre panier est vide.",
      },
      checkOut: {
        title: "Caisse",
        billingDetails: "Détails de Facturation",
        firstName: "Prénom",
        company: "Nom de l'Entreprise",
        Country: "Pays",
        address: "Adresse",
        city: "Ville",
        phone: "Téléphone",
        email: "Adresse Email",
        apartment: "Appartement, étage, etc. (facultatif)",
        methods: "Méthodes de Paiement",
        bank: "Banque (Visa)",
        cash: "Paiement à la Livraison",
        couponCode: "Code Promo",
        postalCode: "Code Postale",
        province: "Province",
        district: "District",
      },
      payment: {
        payment: "Détails de Paiement",
        number: "Numéro de Carte",
        enter: "Entrez votre numéro de carte",
        expirationDate: "Date d'Expiration",
      },
      productPage: {
        relatedItems: "Articles Connexes",
        quantity: "quantite",
        size: "Taille",
        inStock: "En Stock",
        reviews: "Avis",
        review: "Avis",
        1: "Livraison Gratuite",
        1.1: "Entrez votre code postal pour la disponibilité de la livraison",
        2: "Retour de Livraison",
        2.1: "Retours de livraison gratuits pendant 30 jours. Détails",
      },
      contactPage: {
        call: "Appelez-nous",
        available: "Nous sommes disponibles 24/7, 7 jours sur 7.",
        phone: "Téléphone",
        write: "Écrivez-nous",
        fillForm:
          "Remplissez notre formulaire et nous vous contacterons dans les 24 heures.",
        emails: "Emails",
        yourName: "Votre Nom",
        yourEmail: "Votre Email",
        yourPhone: "Votre Numéro de Téléphone",
        yourMessage: "Votre Message",
      },
      aboutPage: {
        title: "À propos",
        story: "Notre Histoire",
        paragraph1:
          "Lancé en 2024, Team-Tchad Export est une place de marché en ligne de premier plan avec une présence active au Tchad. Soutenu par une large gamme de solutions marketing, de données et de services sur mesure, Team-Tchad Export accueille 10 500 vendeurs et 300 marques, servant 3 millions de clients à travers la région.",
        paragraph2:
          "Team-Tchad Export propose plus de 1 million de produits, en pleine croissance. La place de marché offre une gamme diversifiée de catégories, répondant aux divers besoins des consommateurs.",
        card1: "Vendeurs actifs sur notre site",
        card2: "Ventes mensuelles de produits",
        card3: "Clients actifs sur notre site",
        card4: "Vente brute annuelle sur notre site",
        k1: "10,5k",
        k2: "33k",
        k3: "45,5k",
        k4: "25k",
        name1: "Tom Cruise",
        name2: "Tom Hanks",
        name3: "Will Smith",
        name4: "Tom Hardy",
        job1: "Fondateur & Président",
        job2: "CTO",
        job3: "PDG",
        job4: "Designer de Produits",
      },
      accountPage: {
        setMassage: "Détails du compte mis à jour avec succès!",
        welcome: "Bienvenue! ",
        home: "Accueil",
        myAccount: "Mon Compte",
        ManageMyAccount: "Gérer Mon Compte",
        myProfile: "Mon Profil",
        addressBook: "Carnet d'Adresses",
        myPaymentOptions: "Mes Options de Paiement",
        myOrders: "Mes Commandes",
        myReturns: "Mes Retours",
        myCancelations: "Mes Annulations",
        myWishlist: "Ma Liste de Souhaits",
        editYourProfile: "Modifier votre Profil",
        firstName: "Prénom",
        yourFirstName: "votre prénom",
        lastName: "Nom de Famille",
        yourLastName: "votre nom de famille",
        email: "Email",
        yourEmail: "votre email",
        profilePic: "Photo de profil",
        drop: "Déposez l'image ici",
        dragNdrop:
          "Glissez et déposez une image ici, ou cliquez pour en sélectionner une",
        select: "Fichier sélectionné",
        address: "Adresse",
        yourAddress: "votre adresse",
        phoneNumber: "Téléphone",
        province: "Province",
        city: "Ville",
        street: "Rue",
        zipcode: "Code postal",
        passwordChanges: "Modifications du Mot de Passe",
        currentPassword: "Mot de Passe Actuel",
        newPassword: "Nouveau Mot de Passe",
        confirmPassword: "Confirmer le Mot de Passe",
        cancel: "Annuler",
        saveChanges: "Sauvegarder les Modifications",
      },

      signUpPage: {
        title: "Créer un compte",
        enter: "Entrez vos coordonnées ci-dessous:",
        firstname: "Entrez votre prénom",
        lastname: "Entrez votre nom de famille",
        phoneNumber: "Entrez votre téléphone",
        email: "Email",
        password: "Mot de passe",
        createAccount: "Créer un compte",
        withGoogle: "S'inscrire avec Google",
        haveAccount: "Vous avez déjà un compte?",
        login: "Se connecter",
      },
      loginPage: {
        title: "Se connecter à Exclusive",
        enter: "Entrez vos coordonnées ci-dessous:",
        emailOrPhone: "Email ou Numéro de Téléphone",
        password: "Mot de Passe",
        forgot: "Mot de Passe Oublié?",
        notHaveAccount: "Vous n'avez pas de compte?",
        login: "Se Connecter",
        rememberMe: "Se souvenir de moi",
        or: "ou",
        googleLogin: "se connecter avec Google",
      },
      Snackbar: {
        inCart: "Articles déjà dans le panier!",
        movedToCart: "Articles déplacés avec succès dans le panier!",
        noItems: "Aucun article à déplacer dans le panier!",
      },
      category: {
        redTitle: "Catégories",
        title: "Parcourir par Catégorie",
        categories: {
          0: "Agriculture",
          1: "Artisanat",
          2: "Alimentation",
          3: "Textiles",
          4: "Cosmétiques",
          5: "Énergie et Ressources",
          6: "Produits chimiques",
        },
      },
      bestSelling: {
        redTitle: "Ce Mois-ci",
        title: "Meilleures Ventes",
      },
      deal: {
        greenTitle: "Catégories",
        title: "Améliorez Votre Expérience d'Écoute",
        days: "Jours",
        hours: "Heures",
        minutes: "Minutes",
        seconds: "Secondes",
        buyNow: "Achetez Maintenant!",
      },
      allProducts: {
        redTitle: "Nos Produits",
        title: "Explorez Nos Produits",
        products: "Nos Produits",
        byCategory: "Explorer par Catégorie",
        orders: "Commandes",
      },
      featured: {
        redTitle: "En Vedette",
        title: "Projecteurs sur les Produits Tchadiens",
        shopNow: "Achetez Maintenant",
        agriculture: {
          title: "Café",
          description: "Café de haute qualité.",
        },
        handicrafts: {
          title: "Sculptures en Bois",
          description: "Sculptures en bois faites à la main avec soin.",
        },
        food: {
          title: "Banane",
          description: "Bananes de bonne qualité.",
        },
        textiles: {
          title: "Tissu en Coton",
          description: "Tissu en coton de qualité supérieure.",
        },
        cosmetics: {
          title: "Rouge à Lèvres",
          description: "Meilleur rouge à lèvres.",
        },
        energyAndResources: {
          title: "Panneau Solaire",
          description:
            "Panneaux solaires efficaces pour une énergie renouvelable.",
        },
        chemicals: {
          title: "Agent de Nettoyage",
          description: "Agents de nettoyage écologiques.",
        },
      },
      footer: {
        subscribe: "S'abonner",
        offer: "Obtenez 10% de réduction sur votre première commande",
        enterEmail: "Entrez votre email",
        enterPassword: "Entrez votre mot de passe",
        account: "Compte",
        myAccount: "Mon Compte",
        sign: "Connexion / Inscription",
        cart: "Panier",
        wishlist: "Liste de Souhaits",
        shop: "Boutique",
        downloadApp: "Télécharger l'App",
        save: "Économisez 3 $ avec l'App, Nouvel Utilisateur Seulement",
        support: "Support",
        address: "111 Bijoy sarani, Dhaka, DH 1515, Bangladesh",
        quickLinks: "Liens Rapides",
        privacy: "Politique de Confidentialité",
        usage: "Conditions d'Utilisation",
        FAQ: "FAQ",
        Contact: "Contact",
        copyrights: "© Copyright Team Tchad Export. Tous droits réservés",
        allRightsReserved: "© Tous droits réservés",
      },
      dashTopNav: {
        hello: "Bonjour",
        todayIs: "Aujourd'hui, c'est",
        daysOfWeek: {
          0: "Dimanche",
          1: "Lundi",
          2: "Mardi",
          3: "Mercredi",
          4: "Jeudi",
          5: "Vendredi",
          6: "Samedi",
        },
        monthsOfYear: {
          0: "Janvier",
          1: "Février",
          2: "Mars",
          3: "Avril",
          4: "Mai",
          5: "Juin",
          6: "Juillet",
          7: "Août",
          8: "Septembre",
          9: "Octobre",
          10: "Novembre",
          11: "Décembre",
        },
      },
      dashboard: {
        orderComp:{
          backToOrders: "Retour aux commandes",
          shippingAddress: "Adresse de livraison",
          street: "Rue",
          city: "Ville",
          province: "Province",
          district: "District",
          orderInformation: "Informations sur la commande",
          orderStatus: "Statut de la commande",
          totalPrice: "Prix total",
          paymentMethod: "Méthode de paiement",
          approveOrder: "Approuver la commande",
          rejectOrder: "Rejeter la commande",
          approving: "Approbation...",
          rejecting: "Rejet...",
          confirmDelivery: "Confirmer la livraison",
          confirmingDelivery: "Confirmation de la livraison...",
          products: "Produits",
          price: "Prix",
          quantity: "Quantité",
          units: "Unités",
          noOrderFound: "Aucune commande trouvée.",
          failedToFetchOrder: "Échec de la récupération des détails de la commande :",
          failedToUpdateOrderStatus: "Échec de la mise à jour du statut de la commande !",
          orderStatusUpdated: "Statut de la commande mis à jour avec succès !",
          failedToUpdateDeliveryStatus: "Échec de la mise à jour du statut de la livraison",
          deliveryConfirmed: "Livraison confirmée !",
        },
        cardNames: {
          revenue: "Revenu",
          customers: "Clients",
        },
        next: "Suivant",
        previous: "Précédent",
        products: {
          createProduct: "Créer un produit",
          allProducts: "Tous les produits",
          searchPlaceholder: "Rechercher par titre",
          minPricePlaceholder: "Prix min",
          maxPricePlaceholder: "Prix max",
          allCategories: "Toutes les catégories",
          noImage: "Pas d'image",
          noProductsFound: "Aucun produit trouvé.",
          image: "Image",
          title: "Titre",
          price: "Prix",
          moq: "Quantité Minimum (MOQ)",
          category: "Catégorie",
          quantity: "Quantité",
          owner: "Propriétaire",
          actions: "Actions",
          edit: "Modifier",
          delete: "Supprimer",
          more: "Plus",
          loading: "Chargement des produits...",
          error:
            "Erreur lors de la récupération des produits. Veuillez réessayer plus tard.",
        },
        orders: {
          allOrders: "Toutes les commandes",
          searchPlaceholder: "Rechercher par ID de commande ou nom du client",
          orderID: "ID de commande",
          orderer: "Commanditaire",
          products: "Produits",
          date: "Date",
          orderStatus: "Statut de la commande",
          deliveryStatus: "Statut de la livraison",
          totalPrice: "Prix total",
          totalQuantity: "Quantité totale",
          status: "Statut",
          totalAmount: "Montant total",
          paymentMethod: "Mode de paiement",
          shippingAddress: "Adresse de livraison",
          noOrdersFound: "Aucune commande trouvée.",
          actions: "Actions",
          view: "Voir",
          edit: "Modifier",
          delete: "Supprimer",
          loading: "Chargement des commandes...",
          error:
            "Erreur lors de la récupération des commandes. Veuillez réessayer plus tard.",
          previous: "Précédent",
          next: "Suivant",
          orderStatusOptions: {
            pending: "En attente",
            approved: "Approuvée",
            rejected: "Rejetée",
            delivered: "Livrée",
          },
          deliveryFilterOptions: {
            allDeliveries: "Toutes les livraisons",
            delivered: "Livrée",
            notDelivered: "Non livrée",
          },
        },
        allSales:"Toutes les ventes",
        users: {
          allUsers: "Tous les utilisateurs",
          role: "Rôle",
          users: "Utilisateurs",
          findUser: "Trouver un utilisateur...",
          profile: "Photo de profil",
          userId: "ID utilisateur",
          firstName: "Prénom",
          lastName: "Nom",
          email: "Email",
          phoneNumber: "Numéro de téléphone",
          status: "Statut",
          joinedAt: "Rejoint le",
          action: "Action",
        },
        statistics:{
          reportTitle: "Rapport des Statistiques",
          usersByRole: "Utilisateurs par Rôle",
          productsByCategory: "Produits par Catégorie",
          ordersOverview: "Vue d'ensemble des Commandes",
          monthlyRevenue: "Revenus Mensuels",
          topProducts: "Meilleurs Produits",
          userGrowth: "Croissance des Utilisateurs",
          generateReport: "Générer le Rapport",
        }
      },
    },
  },

  rw: {
    translation: {
      font: "font-poppins",
      dir: "ltr",
      topHeader: "Menya ibicuruzwa byiza ku giciro gito cyane.",
      shop: "Duvugane",
      welcome: "Murakaza neza kuri urubuga rw'ubucuruzi",

      home: "Ahabanza",
      contact: "Twandikire",
      about: "Ibibacu",
      signUp: "Iyandikishe",
      account: "Konti Yanjye",
      Dashboard: "Imbonerahamwe",
      manager: "Hita Umuyobozi",
      dashboardNavs: {
        home: "Imbonerahamwe",
        customers: "Abakiriya",
        products: "Ibicuruzwa",
        orders: "Ibisabwa",
        sales: "Ibyagurishijwe",
        statistics: "Imibare",
        topNav: {
          hello: "Muraho nanone!",
        },
      },
      orderPage: {
        underivered: "Ibisabwa Bitaratangazwa",
        derivered: "Ibisabwa Byatanzwe",
        canceled: "Ibisabwa Byahagaritswe",
        underivNotFound: "Nta bisabwa bitaratangazwa",
        derivNotFound: "Nta bisabwa byatanzwe",
        cancelNotFound: "Nta bisabwa byahagaritswe",
      },
      orderCard: {
        orderId: "Nimero y'Icyifuzo",
        orderStatus: "Uko Icyifuzo Kimeze",
        orderDate: "Itariki y'Icyifuzo",
        products: "Ibicuruzwa",
        totalPrice: "Igiciro Rusange",
        cancelOrder: "Hagarika Icyifuzo",
      },
      headerIcons: {
        1: "Genzura Konti Yanjye",
        2: "Ibisabwa Byanjye",
        3: "Ibisabwa Byanjye Byahagaritswe",
        4: "Ibitekerezo Byanjye",
        5: "Sohoka",
      },
      search: "Shakisha...",

      homeSections: {
        row1: {
          col1: [
            "Ubuhinzi",
            "Ibyubatsi",
            "Ibiryo",
            "Imyenda",
            "Ibyo Kwisiga no Kwita ku Mubiri",
            "Ingufu n'Umutungo",
            "Imiti",
          ],
          col2: ["iPhone 14 Series", "Kugeza kuri 10% Kugabanuka", "Gura Ubu"],
        },
        row2: ["Uyu Munsi", "Ubuhinzi", "Iminsi", "Amasaha", "Imminota", "Amasegonda"],
        row3: {
          header: "Ubucuruzi B2B Bwakozwe ku Kigo Cyawe",
          body: "Shakisha urubuga rwakozwe ku bigo kugira ngo bibone ibicuruzwa byiza mu bunini. Kuri Team Tchad Export, dukorera gusa ibikenerwa by'ubucuruzi.",
        },
      },
      removeFromCart: "Kureho mu Gikoni",
      addToCart: "Shyira mu Gitebo",
      new: "GISHYA",
      Search: {
        all: "Byose",
        category: "Icyiciro",
        min: "Gito",
        max: "Kinini",
        placeholder: "Shakisha Ibicuruzwa",
      },
      item: {
        discount: "Kugabanuka",
        expires: "Itariki y'Impera",
        availQuantity: "Umubare Uhari",
        MOQ: "Umubare Ntoya wo Gusaba(MOQ)",
        quantity: "Umubare",
        addCart: "Shyira mu Gitebo",
        addedToCart: "Igicuruzwa kimaze kuba mu gikoni",
      },
      alerts: {
        wishes: {
          success: "Byakunze!",
        },
      },
      categories: {
        general: "Rusange",
        newArrival: "Gishya Kigeze",
        agriculture: "Ubuhinzi",
        handicrafts: "Ibyubatsi",
        food: "Ibiryo",
        textiles: "Imyenda",
        cosmetics: "Ibyo Kwisiga",
        energyAndResources: "Ingufu n'Umutungo",
        chemicals: "Imiti",
      },
      services: {
        0: {
          value: "GUTANGA UBUNTU KANDI BYIHUSE",
          description: "Gutanga ubuntu ku bisabwa byose birenze $140",
        },
        1: {
          value: "SERIVISI Y'ABAKIRIYA 24/7",
          description: "Serivisi y'abakiriya 24/7 nyangurukire",
        },
        2: {
          value: "KWISHYURA AMAFARANGA",
          description: "Turasubiza amafaranga mu minsi 30",
        },
      },
      redButtons: {
        viewAllProducts: "Reba Ibicuruzwa Byose",
        viewAll: "Reba Byose",
        exploreByCategory: "Shakisha Hakurikijwe Icyiciro",
        buyNow: "Gura Ubu",
        sendMassage: "Kohereza Ubutumwa",
        createAccount: "Kora Konti",
        login: "Injira",
        applyCoupon: "Koresha Ikupon",
        processToCheckout: "Komeza Kwishyura",
        placeOrder: "Shyira Icyifuzo",
        backToHomePage: "Subira ku Rupapuro Rw'Ahabanza",
        chooseByCategory: "Hitamo Hakurikijwe Icyiciro",
        createOrder: "Kora Icyifuzo",
      },
      whiteButtons: {
        backToHomePage: "Subira ku Rupapuro Rw'Ahabanza",
        loadMore: "Tangira Ibindi...",
        moveAllToBag: "Kwimura Byose mu Gikoni",
        seeAll: "Reba Byose",
        returnToShop: "Subira ku Duka",
        updateCart: "Vugurura Igikoni",
      },

      wishlist: {
        title: "Inyandiko y'Ibifuza",
        justForYou: "Gusa kuri wowe",
        noWishes: "Nta bifuza",
      },
      cart: {
        header: {
          product: "Igicuruzwa",
          price: "Igiciro",
          quantity: "Umubare",
          subtotal: "Igiciro Gito",
        },
        cartTotal: "Igiciro Rusange cy'Igikoni",
        total: "Igiciro Rusange",
        totalItems: "Ibintu Byose",
        shipping: "Gutanga",
        free: "Ubuntu",
        emptyCart: "Igikoni cyawe kirimo ubusa.",
      },
      checkOut: {
        title: "Kwishyura",
        billingDetails: "Amakuru y'Inyandiko",
        firstName: "Izina Ry'Imbere",
        company: "Izina ry'Ikigo",
        Country: "Igihugu",
        address: "Aderesi y'Umuhanda",
        city: "Umujyi",
        phone: "Telefone",
        email: "Aderesi ya Imeyile",
        apartment: "Inzu, urwego, nibindi (bitari ngombwa)",
        methods: "Uburyo bwo Kwishyura",
        bank: "Banki (Visa)",
        cash: "Amafaranga Igihe Bitanzwe",
        couponCode: "Kode ya Ikupon",
        postalCode: "Kode ya Posita",
        province: "Intara",
        district: "Akarere",
      },
      payment: {
        payment: "Amakuru y'Kwishyura",
        number: "Nimero y'Ikarita",
        enter: "Injiza nimero y'ikarita yawe",
        expirationDate: "Itariki y'Impera",
      },
      productPage: {
        relatedItems: "Ibintu Bijyanye",
        quantity: "umubare",
        size: "Ubunini",
        inStock: "Birahari",
        reviews: "Ibitekerezo",
        review: "Igitekerezo",
        1: "Gutanga Ubuntu",
        1.1: "Injiza kode ya posita yawe kugira ngo umenye niba birashobora gutangwa",
        2: "Kugarura Gutanga",
        2.1: "Kugarura ubuntu iminsi 30. Amakuru",
      },
      contactPage: {
        call: "Duhagurure",
        available: "Turahari 24/7, iminsi 7 mu cyumweru.",
        phone: "Telefone",
        write: "Dukore",
        fillForm: "Uzuza ifishi yacu kandi tuzagukurikirana mu masaha 24.",
        emails: "Imeyile",
        yourName: "Izina Ryawe",
        yourEmail: "Imeyile Yawe",
        phoneNumber: "Nimero ya Telefone Yawe",
        yourMessage: "Ubutumwa Bwawe",
      },
      aboutPage: {
        title: "Ibibacu",
        story: "Inkuru Yacu",
        paragraph1:
          "Byatangijwe mu 2024, Team-Tchad Export ni isoko ry'imbere ry'ubucuruzi ku rubuga rifite uruhare rukomeye muri Chadi. Rishyigikiwe n'ubwoko bunini bw'ibikorwa byo kwamamaza, amakuru, n'ibikorwa by'imbuga, Team-Tchad Export ikubana n'abaguzi 10,500 n'ibimenyetso 300, ikorera abakiriya 3 miliyoni mu karere.",
        paragraph2:
          "Team-Tchad Export itanga ibicuruzwa birenze miliyoni 1, ikura ku muvuduko mwinshi. Isoko ritanga urutonde rw'ibyiciro bitandukanye, ruhaza ibikenerwa bitandukanye by'abaguzi.",
        card1: "Abaguzi bakora ku rubuga rwacu",
        card2: "Ibicuruzwa Byagurishijwe Buri Kwezi",
        card3: "Abakiriya bakora ku rubuga rwacu",
        card4: "Igicuruzwa rusange cy'umwaka ku rubuga rwacu",
        k1: "10.5k",
        k2: "33k",
        k3: "45.5k",
        k4: "25k",
        name1: "Tom Cruise",
        name2: "Tom Hanks",
        name3: "Will Smith",
        name4: "Tom Hardy",
        job1: "Uwashinze & Perezida",
        job2: "Umuyobozi Mukuru w'Ikoranabuhanga",
        job3: "Umuyobozi Mukuru",
        job4: "Umushushanya w'Ibicuruzwa",
      },
      accountPage: {
        setMassage: "Amakuru y'konti yavuguruwe neza!",
        welcome: "Murakaza neza! ",
        home: "Ahabanza",
        myAccount: "Konti Yanjye",
        ManageMyAccount: "Genzura Konti Yanjye",
        myProfile: "Umwirondoro Wanjye",
        addressBook: "Igitabo cy'Aderesi",
        myPaymentOptions: "Amahitamo Yanjye yo Kwishyura",
        myOrders: "Ibisabwa Byanjye",
        myReturns: "Ibisabwa Byanjye Byagarutse",
        myCancelations: "Ibisabwa Byanjye Byahagaritswe",
        myWishlist: "Inyandiko y'Ibifuza",
        editYourProfile: "Hindura Umwirondoro Wawe",
        firstName: "Izina Ry'Imbere",
        yourFirstName: "izina ryawe ry'imbere",
        lastName: "Izina Rya Nyuma",
        yourLastName: "izina ryawe rya nyuma",
        email: "Imeyile",
        yourEmail: "imeyile yawe",
        phoneNumber: "Telefone",
        province: "Intara",
        city: "Umujyi",
        street: "Umuhanda",
        zipcode: "Kode ya Zip",
        profilePic: "Ifoto y'Umwirondoro",
        drop: "Guca ifoto hano",
        dragNdrop: "Kurura ifoto hano, cyangwa kanda uhitemo",
        select: "Idosiye yatoranyijwe",
        address: "Aderesi",
        yourAddress: "aderesi yawe",
        passwordChanges: "Guhindura Ijambo Ry'Ibanga",
        currentPassword: "Ijambo Ry'Ibanga Ry'Ubu",
        newPassword: "Ijambo Ry'Ibanga Rishya",
        confirmPassword: "Emeza Ijambo Ry'Ibanga",
        cancel: "Hagarika",
        saveChanges: "Bika Impinduka",
      },

      signUpPage: {
        title: "Kora konti",
        enter: "Injiza amakuru yawe hasi:",
        firstname: "Izina ry'imbere",
        lastname: "Izina rya nyuma",
        phoneNumber: "Telefone",
        email: "Imeyile",
        password: "Ijambo ry'ibanga",
        createAccount: "Kora Konti",
        withGoogle: "Iyandikishe na Google",
        haveAccount: "Usanzwe ufite konti?",
        login: "Injira",
      },
      loginPage: {
        title: "Injira muri Exclusive",
        enter: "Injiza amakuru yawe hasi:",
        email: "Imeyile",
        password: "Ijambo ry'ibanga",
        forgot: "Wibagiwe Ijambo ry'Ibanga?",
        notHaveAccount: "Ntufite konti?",
        login: "Injira",
        rememberMe: "Wibuke",
        or: "cyangwa",
        googleLogin: "injira na Google",
      },
      Snackbar: {
        inCart: "Ibintu bimaze kuba mu gikoni!",
        movedToCart: "Ibintu byimukijwe mu gikoni neza!",
        noItems: "Nta bintu byo kwimukira mu gikoni!",
      },
      category: {
        redTitle: "Ibyiciro",
        title: "Shakisha Hakurikijwe Icyiciro",
        categories: {
          0: "Ubuhinzi",
          1: "Ibyubatsi",
          2: "Ibiryo",
          3: "Imyenda",
          4: "Ibyo Kwisiga",
          5: "Ingufu n'Umutungo",
          6: "Imiti",
        },
      },
      bestSelling: {
        redTitle: "Uku Kwezi",
        title: "Ibicuruzwa Byiza Byagurishijwe",
      },
      deal: {
        greenTitle: "Ibyiciro",
        title: "Ongera Urutonde rw'Ibicuruzwa Ukunda Nacu",
        days: "Iminsi",
        hours: "Amasaha",
        minutes: "Imminota",
        seconds: "Amasegonda",
        buyNow: "Gura Ubu!",
      },
      allProducts: {
        redTitle: "Ibicuruzwa Byacu",
        title: "Shakisha Ibicuruzwa Byacu",
        products: "Ibicuruzwa Byose",
        byCategory: "Shakisha Hakurikijwe Icyiciro",
        orders: "Ibisabwa",
      },
      featured: {
        redTitle: "Byahagaritswe",
        title: "Ibicuruzwa by'Abacha Byahagaritswe",
        shopNow: "Gura Ubu",
        agriculture: {
          title: "Ikawa",
          description: "Ikawa y'ubwiza buhebuje.",
        },
        handicrafts: {
          title: "Ibyubatsi by'Ibiti",
          description: "Ibyubatsi by'ibiti byubatswe neza.",
        },
        food: {
          title: "Umuneke",
          description: "Umuneke mwiza.",
        },
        textiles: {
          title: "Igitambara cy'Ipamba",
          description: "Igitambara cy'ipamba cy'ubwiza buhebuje.",
        },
        cosmetics: {
          title: "Irangi ry'Iminwe",
          description: "Irangi ry'iminwe ryiza cyane.",
        },
        energyAndResources: {
          title: "Ikibaho cy'Iziko",
          description: "Ibikibaho by'iziko bifasha mu ingufu z'ubunyangamugayo.",
        },
        chemicals: {
          title: "Imiti yo Gusukura",
          description: "Imiti yo gusukura idangiza ibidukikije.",
        },
      },
      footer: {
        subscribe: "Iyandikishe",
        offer: "Bona 10% ku cyifuzo cyawe cya mbere",
        enterEmail: "Injiza imeyile yawe",
        enterPassword: "Injiza ijambo ry'ibanga ryawe",
        account: "Konti",
        myAccount: "Konti Yanjye",
        sign: "Injira / Iyandikishe",
        cart: "Igikoni",
        wishlist: "Inyandiko y'Ibifuza",
        shop: "Duka",
        downloadApp: "Kuramo Porogaramu",
        save: "Bika $3 na Porogaramu Nshya y'Ukoresha",
        support: "Ubufasha",
        address: "111 Bijoy sarani, Dhaka, DH 1515, Bangladesh",
        quickLinks: "Amakuru y'Ibyihuse",
        privacy: "Amategeko y'Ibanga",
        usage: "Amabwiriza yo Gukoresha",
        FAQ: "Ibibazo Bikunze Kubazwa",
        Contact: "Twandikire",
        copyrights: "© Uburenganzira Team Tchad Export 2024. Uburenganzira bwose bwabitswe",
        allRightsReserved: "© Uburenganzira bwose bwabitswe",
      },
      dashTopNav: {
        hello: "Muraho",
        todayIs: "Uyu Munsi ni",
        daysOfWeek: {
          0: "Ku Cyumweru",
          1: "Ku wa Mbere",
          2: "Ku wa Kabiri",
          3: "Ku wa Gatatu",
          4: "Ku wa Kane",
          5: "Ku wa Gatanu",
          6: "Ku wa Gatandatu",
        },
        monthsOfYear: {
          0: "Mutarama",
          1: "Gashyantare",
          2: "Werurwe",
          3: "Mata",
          4: "Gicurasi",
          5: "Kamena",
          6: "Nyakanga",
          7: "Kanama",
          8: "Nzeri",
          9: "Ukwakira",
          10: "Ugushyingo",
          11: "Ukuboza",
        },
      },
      dashboard: {
        orderComp: {
          backToOrders: "Subira ku Bisabwa",
          shippingAddress: "Aderesi yo Kohereza",
          street: "Umuhanda",
          city: "Umujyi",
          province: "Intara",
          district: "Akarere",
          orderInformation: "Amakuru y'Icyifuzo",
          orderStatus: "Uko Icyifuzo Kimeze",
          totalPrice: "Igiciro Rusange",
          paymentMethod: "Uburyo bwo Kwishyura",
          approveOrder: "Emeza Icyifuzo",
          rejectOrder: "Anga Icyifuzo",
          approving: "Kemeza...",
          rejecting: "Anga...",
          confirmDelivery: "Emeza Gutanga",
          confirmingDelivery: "Kemeza Gutanga...",
          products: "Ibicuruzwa",
          price: "Igiciro",
          quantity: "Umubare",
          units: "Ibipimo",
          noOrderFound: "Nta cyifuzo kibonetse.",
          failedToFetchOrder: "Byanze kubona amakuru y'icyifuzo:",
          failedToUpdateOrderStatus: "Byanze kuvugurura uko icyifuzo kimeze!",
          orderStatusUpdated: "Uko icyifuzo kimeze cyavuguruwe neza!",
          failedToUpdateDeliveryStatus: "Byanze kuvugurura uko gutanga kumeze",
          deliveryConfirmed: "Gutanga kwemejwe!",
        },
        cardNames: {
          revenue: "Inyungu",
          customers: "Abakiriya",
        },
        next: "Ibikurikira",
        previous: "Ibya Mbere",
        users: {
          allUsers: "Abakoresha Bose",
          role: "Uruhare",
          users: "Abakoresha",
          findUser: "shakisha Umukoresha...",
          profile: "Ifoto y'Umwirondoro",
          userId: "Nimero y'Umukoresha",
          firstName: "Izina Ry'Imbere",
          lastName: "Izina Rya Nyuma",
          email: "Imeyile",
          phoneNumber: "Nimero ya Telefone",
          status: "Uko Bimeze",
          joinedAt: "Yinjiye Ku",
          action: "Igikorwa",
        },
        products: {
          createProduct: "Kora Igicuruzwa",
          allProducts: "Ibicuruzwa Byose",
          searchPlaceholder: "Shakisha hakurikijwe umutwe",
          minPricePlaceholder: "Igiciro gito",
          maxPricePlaceholder: "Igiciro kinini",
          allCategories: "Ibyiciro Byose",
          noImage: "Nta foto",
          noProductsFound: "Nta bicuruzwa byabonetse.",
          image: "Ifoto",
          title: "Umutwe",
          price: "Igiciro",
          moq: "MOQ",
          category: "Icyiciro",
          quantity: "Umubare",
          owner: "Nyir'ubwite",
          actions: "Ibikorwa",
          edit: "Hindura",
          delete: "Siba",
          more: "Byinshi",
          previous: "Ibya Mbere",
          next: "Ibikurikira",
          loading: "Gutangiza Ibicuruzwa...",
          error: "Ikosa mu kubona ibicuruzwa. Nyamuneka gerageza nanone nyuma.",
        },
        allSales: "Ibyagurishijwe Byose",
        orders: {
          allOrders: "Ibisabwa Byose",
          searchPlaceholder: "Shakisha hakurikijwe nimero y'icyifuzo cyangwa izina ry'umukiriya",
          orderID: "Nimero y'Icyifuzo",
          orderer: "Uwasabye",
          products: "Ibicuruzwa",
          date: "Itariki",
          orderStatus: "Uko Icyifuzo Kimeze",
          deliveryStatus: "Uko Gutanga Kumeze",
          totalPrice: "Igiciro Rusange",
          totalQuantity: "Umubare Rusange",
          status: "Uko Bimeze",
          totalAmount: "Igiciro Rusange",
          paymentMethod: "Uburyo bwo Kwishyura",
          shippingAddress: "Aderesi yo Kohereza",
          noOrdersFound: "Nta bisabwa byabonetse.",
          actions: "Ibikorwa",
          view: "Reba",
          edit: "Hindura",
          delete: "Siba",
          loading: "Gutangiza Ibisabwa...",
          error: "Ikosa mu kubona ibisabwa. Nyamuneka gerageza nanone nyuma.",
          previous: "Ibya Mbere",
          next: "Ibikurikira",
          orderStatusOptions: {
            pending: "Bitegereje",
            approved: "Byemejwe",
            rejected: "Byangwe",
            delivered: "Byatanzwe",
          },
          deliveryFilterOptions: {
            allDeliveries: "Gutanga Kwose",
            delivered: "Byatanzwe",
            notDelivered: "Bitaratanzwa",
          },
        },
        statistics: {
          reportTitle: "Raporo y'Imibare",
          usersByRole: "Abakoresha Hakurikijwe Uruhare",
          productsByCategory: "Ibicuruzwa Hakurikijwe Icyiciro",
          ordersOverview: "Incamake y'Ibisabwa",
          monthlyRevenue: "Inyungu z'Buri Kwezi",
          topProducts: "Ibicuruzwa Byambere",
          userGrowth: "Kwiyongera kw'Abakoresha",
          generateReport: "Kora Raporo",
        },
      },
    },
  },
};

// Initialize i18n
i18n.use(initReactI18next).init({
  lng: defaultLang,
  resources,
  keySeparator: ".",
  interpolation: { escapeValue: false },
});

export default i18n;
