import i18n from "../components/LangConfig";

const categories = {
  0: "Agriculture",
  1: "Food",
  // 2: "Handicrafts",
  // 3: "Textiles",
  // 4: "Cosmetics",
  // 5: "Energy and Resources",
  // 6: "Chemicals",
};

let idCounter = 0;

export const ITEMS = [
  {
    id: String(idCounter++),
    imageSrc: "../assets/honey.png",
    title: i18n.t("itemsArray.0.title"),
    price: 960,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    quantity: 0,
    type: i18n.t("itemsArray.0.type"),
    details: i18n.t("itemsArray.0.details"),
    category: categories[5],
  },
  {
    id: String(idCounter++),
    imageSrc: "../assets/eggs.png",
    title: i18n.t("itemsArray.1.title"),
    price: 360,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    quantity: 0,
    type: i18n.t("itemsArray.1.type"),
    details: i18n.t("itemsArray.1.details"),
    category: categories[3], // Assuming camera-related items fall under Textiles
  },
  {
    id: String(idCounter++),
    imageSrc: "../assets/handwoven.png",
    price: 100,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    quantity: 0,
    title: i18n.t("itemsArray.2.title"),
    type: i18n.t("itemsArray.2.type"),
    details: i18n.t("itemsArray.2.details"),
    category: categories[2], // Assuming dog food falls under Food
  },
  {
    id: String(idCounter++),
    imageSrc: "../assets/eggs.png",
    price: 700,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    quantity: 0,
    title: i18n.t("itemsArray.3.title"),
    type: i18n.t("itemsArray.3.type"),
    details: i18n.t("itemsArray.3.details"),
    category: categories[5], // Assuming laptop-related items fall under Energy and Resources
  },
  {
    id: String(idCounter++),
    imageSrc: "../assets/pot.png",
    price: 500,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    quantity: 0,
    title: i18n.t("itemsArray.4.title"),
    type: i18n.t("itemsArray.4.type"),
    details: i18n.t("itemsArray.4.details"),
    category: categories[4], // Assuming cream falls under Cosmetics
  },
  {
    id: String(idCounter++),
    imageSrc: "../assets/eggs.png",
    price: 660,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: 40,
    quantity: 0,
    title: i18n.t("itemsArray.5.title"),
    type: i18n.t("itemsArray.5.type"),
    details: i18n.t("itemsArray.5.details"),
    category: categories[4], // Assuming glasses fall under Cosmetics
  },
  {
    id: String(idCounter++),
    imageSrc: "../assets/eggs.png",
    price: 660,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: 40,
    quantity: 0,
    title: i18n.t("itemsArray.6.title"),
    type: i18n.t("itemsArray.6.type"),
    details: i18n.t("itemsArray.6.details"),
    category: categories[3], // Assuming jacket falls under Textiles
  },
  {
    id: String(idCounter++),
    imageSrc: "../assets/eggs.png",
    price: 360,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: 40,
    quantity: 0,
    title: i18n.t("itemsArray.7.title"),
    type: i18n.t("itemsArray.7.type"),
    details: i18n.t("itemsArray.7.details"),
    category: categories[1], // Assuming bookshelf falls under Handicrafts
  },
  {
    id: String(idCounter++),
    imageSrc: "../assets/eggs.png",
    price: 160,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: 40,
    quantity: 0,
    title: i18n.t("itemsArray.8.title"),
    type: i18n.t("itemsArray.8.type"),
    details: i18n.t("itemsArray.8.details"),
    category: categories[5], // Assuming headphones fall under Energy and Resources
  },
  {
    id: String(idCounter++),
    imageSrc: "../assets/eggs.png",
    price: 1160,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: 40,
    quantity: 0,
    title: i18n.t("itemsArray.9.title"),
    type: i18n.t("itemsArray.9.type"),
    details: i18n.t("itemsArray.9.details"),
    category: categories[3], // Assuming bag falls under Textiles
  },
  {
    id: String(idCounter++),
    imageSrc: "../assets/eggs.png",
    price: 360,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: 40,
    quantity: 0,
    title: i18n.t("itemsArray.10.title"),
    type: i18n.t("itemsArray.10.type"),
    details: i18n.t("itemsArray.10.details"),
    category: categories[3], // Assuming coat falls under Textiles
  },
  {
    id: String(idCounter++),
    imageSrc: "../assets/eggs.png",
    price: 160,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: 40,
    quantity: 0,
    title: i18n.t("itemsArray.11.title"),
    type: i18n.t("itemsArray.11.type"),
    details: i18n.t("itemsArray.11.details"),
    category: categories[4], // Assuming glasses fall under Cosmetics
  },
  {
    id: String(idCounter++),
    imageSrc: "../assets/eggs.png",
    price: 1160,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: 35,
    quantity: 0,
    title: i18n.t("itemsArray.12.title"),
    type: i18n.t("itemsArray.12.type"),
    details: i18n.t("itemsArray.12.details"),
    category: categories[5], // Assuming keyboard falls under Energy and Resources
  },
  {
    id: String(idCounter++),
    imageSrc: "../assets/eggs.png",
    price: 400,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: 30,
    quantity: 0,
    title: i18n.t("itemsArray.13.title"),
    type: i18n.t("itemsArray.13.type"),
    details: i18n.t("itemsArray.13.details"),
    category: categories[5], // Assuming TV falls under Energy and Resources
  },
  {
    id: String(idCounter++),
    imageSrc: "../assets/chair.png",
    price: 400,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: 25,
    quantity: 0,
    title: i18n.t("itemsArray.14.title"),
    type: i18n.t("itemsArray.14.type"),
    details: i18n.t("itemsArray.14.details"),
    category: categories[1], // Assuming chair falls under Handicrafts
  },
  {
    id: String(idCounter++),
    imageSrc: "../assets/rice.png",
    price: 1200,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    state: 1,
    quantity: 0,
    title: i18n.t("itemsArray.15.title"),
    type: i18n.t("itemsArray.15.type"),
    details: i18n.t("itemsArray.15.details"),
    category: categories[5], // Assuming JBL Boombox falls under Energy and Resources
  },
  {
    id: String(idCounter++),
    imageSrc: "../assets/tomatoes.png",
    price: 1200,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    state: 1,
    quantity: 0,
    title: i18n.t("itemsArray.16.title"),
    type: i18n.t("itemsArray.16.type"),
    details: i18n.t("itemsArray.16.details"),
    category: categories[4], // Assuming perfume falls under Cosmetics
  },
  {
    id: String(idCounter++),
    imageSrc: "../assets/cofee.png",
    price: 1200,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    state: 1,
    quantity: 0,
    title: i18n.t("itemsArray.17.title"),
    type: i18n.t("itemsArray.17.type"),
    details: i18n.t("itemsArray.17.details"),
    category: categories[5], // Assuming phone falls under Energy and Resources
  },
  {
    id: String(idCounter++),
    imageSrc: "../assets/rice.png",
    price: 1200,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    state: 1,
    quantity: 0,
    title: i18n.t("itemsArray.18.title"),
    type: i18n.t("itemsArray.18.type"),
    details: i18n.t("itemsArray.18.details"),
    category: categories[5], // Assuming Playstation falls under Energy and Resources
  },
  {
    id: String(idCounter++),
    imageSrc: "../assets/tomatoes.png",
    price: 1200,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    state: 1,
    quantity: 0,
    title: i18n.t("itemsArray.19.title"),
    type: i18n.t("itemsArray.19.type"),
    details: i18n.t("itemsArray.19.details"),
    category: categories[5], // Assuming speakers fall under Energy and Resources
  },
  {
    id: String(idCounter++),
    imageSrc: "../assets/cofee.png",
    price: 1200,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    state: 1,
    quantity: 0,
    title: i18n.t("itemsArray.20.title"),
    type: i18n.t("itemsArray.20.type"),
    details: i18n.t("itemsArray.20.details"),
    category: categories[3], // Assuming women's collections fall under Textiles
  },
  {
    id: String(idCounter++),
    imageSrc: "../assets/rice.png",
    price: 400,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    state: 1,
    quantity: 0,
    title: i18n.t("itemsArray.21.title"),
    type: i18n.t("itemsArray.21.type"),
    details: i18n.t("itemsArray.21.details"),
    category: categories[3], // Assuming shoes fall under Textiles
  },
  {
    id: String(idCounter++),
    imageSrc: "../assets/tomatoes.png",
    price: 400,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    state: 1,
    quantity: 0,
    title: i18n.t("itemsArray.22.title"),
    type: i18n.t("itemsArray.21.type"),
    details: i18n.t("itemsArray.22.details"),
    category: categories[0], // Assuming shoes fall under Textiles
  },
  {
    id: String(idCounter++),
    imageSrc: "../assets/rice.png",
    price: 400,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    state: 1,
    quantity: 0,
    title: i18n.t("itemsArray.23.title"),
    type: i18n.t("itemsArray.21.type"),
    details: i18n.t("itemsArray.23.details"),
    category: categories[0], // Assuming shoes fall under Textiles
  },
  {
    id: String(idCounter++),
    imageSrc: "../assets/cofee.png",
    price: 400,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    state: 1,
    quantity: 0,
    title: i18n.t("itemsArray.24.title"),
    type: i18n.t("itemsArray.21.type"),
    details: i18n.t("itemsArray.24.details"),
    category: categories[0], // Assuming shoes fall under Textiles
  },
];
